name: Build, test and publish
on:
  push:
    branches: [ master ]   

jobs:
  WPF:
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      dotnet-version: 7.0.x
      project-path: src/apps/Ratbuddyssey.Apps.Wpf
      asset-path1: src/apps/Ratbuddyssey.Apps.Wpf/bin/Release/Ratbuddyssey.Apps.Wpf_net4.6.2.zip
      asset-name1: Ratbuddyssey.Apps.Wpf_net4.6.2.zip
      asset-content-type1: application/zip
      asset-path2: src/apps/Ratbuddyssey.Apps.Wpf/bin/Release/Ratbuddyssey.Apps.Wpf_net7.0-windows.zip
      asset-name2: Ratbuddyssey.Apps.Wpf_net7.0-windows.zip
      asset-content-type2: application/zip

  Avalonia:
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      dotnet-version: 7.0.x
      project-path: src/apps/Ratbuddyssey.Apps.Avalonia

  #UWP:
  #  uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
  #  with:
  #    os: windows-2022
  #    #dotnet-version: 7.0.x
  #    #install-latest-msbuild: true
  #    project-path: /target:apps\Ratbuddyssey_Apps_Uwp
  #    use-msbuild: true
  #    generate-build-number: false

  #WinUI:
  #  uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
  #  with:
  #    os: windows-2022
  #    #dotnet-version: 7.0.x
  #    #install-latest-msbuild: true
  #    project-path: /target:apps\Ratbuddyssey_Apps_WinUI
  #    use-msbuild: true
  #    generate-build-number: false
  #    windows-sdk-version: 19041

  WebAssembly:
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      dotnet-version: 7.0.x
      project-path: src/apps/Uno/Ratbuddyssey.Apps.Uno.WebAssembly
      additional-dotnet-version: 5.0.x
      deploy-web-assembly-path: src/apps/Uno/Ratbuddyssey.Apps.Uno.WebAssembly/bin/Release/net6.0/dist
      generate-build-number: false