name: Build, test and publish
on: [ push ]

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-2022
      additional-dotnet-version: 5.0.x
      use-msbuild: true
      run-tests: false
      asset-path1: src/apps/Ratbuddyssey/bin/Release/Ratbuddyssey_net4.6.1.zip
      asset-name1: Ratbuddyssey_net4.6.1.zip
      asset-content-type1: application/zip
      asset-path2: src/apps/Ratbuddyssey/bin/Release/Ratbuddyssey_net6.0-windows.zip
      asset-name2: Ratbuddyssey_net6.0-windows.zip
      asset-content-type2: application/zip